name: RealmsCraft
version: ${project.version}
main: me.copdead.realmscraft.RealmsCraft
api-version: 1.13
authors: [RyanKeller]
description: A plugin for realmscraft questing
commands:
    revive:
        description: revives a player
        usage: /<command> <player>
    afterlife:
        description: sets the location players go when they die
        usage: /<command> <world> <x> <y> <z>
    selectclass:
        description: gives a player a class select book
        usage: /<command> <player>
    investigate:
        description: begin spectating a players perspective
        usage: /<command> <player>
    confirmspeak:
        description: helper command for 'speak' spell.
        usage: /<command> <string> <player>
    nick:
        description: allows players to set an IC name. This name will appear in chat messages.
        usage: /<command> <player> <name>